### ISSUE TITLE
What is the status of Rubybench?

### ISSUE THREAD

**Issue by ExternalReality** [ruby-bench/ruby-bench-suite#123]
Wondering is this work is still ongoing, merged with other work, or etc. I would be interested in any writeup about lessons learned, etc. Thank you.

**Comment by noahgibbs** [comment]
At this point, work is *not* going forward. A writeup is a good idea and I should do it, but no promises on schedule :-)

The short version is: Discourse is a very difficult benchmark for the same reasons that make it valuable, and the ongoing maintenance work to keep it working are substantial.

There's a small Discourse benchmark in the YJIT benchmarks (https://github.com/Shopify/yjit-extra-benchmarks/tree/main/benchmarks/discourse) and it has roughly the same problem -- it requires constant manual maintenance to keep it compatible with head-of-master Ruby.

Rails-Ruby-Bench didn't have that exact problem. It was locked to a very specific Discourse version and, with one exception, never changed version. But the type and amount of effort is similar.

**Comment by ExternalReality** [comment]
Thank you sir. I look forward to one day seeing a potential writeup :-)
