### ISSUE TITLE
bm_io_select3 memory benchmark problem

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-suite#2]
![screenshot from 2015-02-06 22 14 09](https://cloud.githubusercontent.com/assets/4335742/6080569/8a80ee60-ae4d-11e4-9782-cd93465316f6.png)

**Comment by SamSaffron** [comment]
too many open files is easy to fix, its just a linux setting 

http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by tgxworld** [comment]
@SamSaffron Hmm seems like increasing the limit doesn't help due to https://github.com/ruby-bench/ruby-bench-suite/blob/master/ruby/benchmarks/bm_io_select3.rb#L12. I'm not sure about the intention of the `-10` but if I changed it to `-11`, it'll work for all limits.

**Comment by tgxworld** [comment]
I'm thinking of increasing the limit and fixing `max` to a number smaller than the limit. `ulimit -Sn 4096; max = 2000` for instance
