### ISSUE TITLE
Add to_a to bm_activerecord_scope.rb

### ISSUE THREAD

**Issue by SamSaffron** [ruby-bench/ruby-bench-suite#21]
The bench is just testing how long it takes to make the relation, we want to get data out, making the relation is not an interesting bench. 

Add `to_a` to the end 

cc @tgxworld

**Comment by tgxworld** [comment]
Related: https://github.com/ruby-bench/ruby-bench-suite/pull/20

**Comment by tgxworld** [comment]
Resolved in https://github.com/tgxworld/ruby-bench-suite/commit/1724eb41d39c05361bfb6e6aa257dcacb3c3abad
