### ISSUE TITLE
I think Discourse bench is broken

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-suite#42]
results are not being posted.

**Comment by SamSaffron** [comment]
ouch, we should try locally and see whats up

**Comment by tgxworld** [comment]
@SamSaffron most likely due to the recent changes I made :stuck_out_tongue:

**Comment by tgxworld** [comment]
```
rake aborted!
NoMethodError: undefined method `to_ary' for 86400:Fixnum
  (in /discourse/app/assets/javascripts/discourse/lib/emoji/emoji.js.erb)
/discourse/lib/discourse_redis.rb:57:in `block (2 levels) in <class:DiscourseRedis>'
/discourse/lib/cache.rb:48:in `write_entry'
/discourse/app/models/emoji.rb:27:in `standard'
/discourse/app/assets/javascripts/discourse/lib/emoji/emoji.js.erb:11:in `block in singleton class'
/discourse/app/assets/javascripts/discourse/lib/emoji/emoji.js.erb:-5:in `instance_eval'
/discourse/app/assets/javascripts/discourse/lib/emoji/emoji.js.erb:-5:in `singleton class'
/discourse/app/assets/javascripts/discourse/lib/emoji/emoji.js.erb:-7:in `__tilt_69944769901500'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
Bundling assets
script/bench.rb:343:in `kill': no implicit conversion from nil to integer (TypeError)
    from script/bench.rb:343:in `ensure in <main>'
    from script/bench.rb:343:in `<main>'
```

Ruby commit `0970a928ef5079aa1e4745fe3a79af8685a82f46` onwards.

**Comment by SamSaffron** [comment]
weird ... never seen that before, can you dump tmp directory and assets dir
and redis ?

**Comment by tgxworld** [comment]
Fixed!

**Comment by njt1982** [comment]
@tgxworld What did you do to fix it?

**Comment by njt1982** [comment]
We fixed it. The problem we had was "launcher rebuilt [ID]" did a git pull and updated the launched script. This changed LOADS of stuff.

Most importantly:

a) It updated the base image which switched us from Ruby 2.0.0 to Ruby 2.3.0 (which caused this to_ary error **I THINK**).
b) As we were using the non-version locked postgres template, it caused our Postgres DB to be upgraded to 9.5).

**Comment by tgxworld** [comment]
@njt1982 I'm not sure if this is the right repository. Is this related to your Discourse instance? If it is and something is broken with the launcher script, https://github.com/discourse/discourse_docker should be the right place to open the issue

**Comment by njt1982** [comment]
You're right - mine is about the discourse docker, however on googling the error this post comes up top. I assumed the cause was similar?!

**Comment by marianposaceanu** [comment]
I know this issue is quite old and closed but it still comes up in the Google results - I was upgrading to Rails 4.1.16 and removing the hiredis gem fixed the problem. Hopefully it will be of some help.
