### ISSUE TITLE
New Ruby Benchmarks.

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-suite#53]
https://github.com/ruby/ruby/commits/trunk/benchmark

Ok I think we need to start automating this. Perhaps an automated PR whenever something changes

**Comment by benoittgt** [comment]
I have no idea how to do what, but will love to pair on a PR.

**Comment by tgxworld** [comment]
Hey @benoittgt! Thanks for your interest. Basically we need to copy the new benchmarks from Ruby into this repository.
